In [1]:
import numpy as np
import emcee
from my_script import run_myradex_of,mol_data

### Papadopoulos et al. 2014 ###

In [2]:
Tkin=10**2.6
nH2=10**4
Kvir=10
size=214
Tdust=30
ropH2=3
abundance_Cp=np.array([3e-4,1e-5,1e-6])              # CII abundance
abundance_O=2.9e-4
nelec=abundance_Cp*2*nH2                             # electron density

In [3]:
G_FUV=5645*(Tdust/50)**6                             # eq.3
gamma=(G_FUV*Tkin**0.5)/nelec
epsilon_ph=4.9e-2/(1+4e-3*gamma**0.73)+3.65e-2*(Tkin/1e4)**0.7/(1+2e-4*gamma)
Gamma_pe=2e-24*epsilon_ph*nH2*G_FUV
Gamma_pe

array([1.82332223e-19, 3.65879740e-20, 7.32024111e-21])

In [4]:
f_g_d=Tkin/Tdust
Lambda_g_d=1.4e-32*nH2**2*(f_g_d-1)/f_g_d*Tkin**1.5
Lambda_g_d

1.0282585113853013e-20

In [5]:
co_mol=mol_data('/home/zj/Documents/radex_mol/','co.dat')
Tbs=run_myradex_of(Tkin=Tkin,nH2=nH2,abundance_Kvir=1e-4/Kvir,molecule=co_mol)[0]

In [6]:
lum_Lsun=2*co_mol.rad_data[:,3]**2*1.380649e-16/3e10**2*Tbs*np.pi/4/np.log(2)*(size*3.08e18)**2*(300/3e5*co_mol.rad_data[:,3])/3.8263e33
Ncol=3.08e18*nH2/Kvir*1/(0.65*1.5**0.5*(nH2/1e3)**0.5)
mass=Ncol*(2*1.66053904e-24)*np.pi/4/np.log(2)*size**2*3.08567758e18**2/1.98855e33
Lambda_CO=8.77e-33*nH2*np.sum(lum_Lsun)/mass*1e9

In [7]:
Lambda_Cp=7.9e-23*abundance_Cp*nH2**2*np.exp(-92.2/Tkin)
Lambda_Cp

array([1.88004183e-18, 6.26680610e-20, 6.26680610e-21])

In [8]:
Lambda_Oi=2.27e-24*abundance_O*nH2**2*Tkin**0.32*np.exp(-228/Tkin)
Lambda_Oi

2.521732502963257e-19

In [9]:
R10=26.8*ropH2*(1+1/5*np.exp(510/Tkin)*(1+54/nH2))/(1+3/7*np.exp(845/Tkin)*(1+1e3/nH2))
Lambda_H2=2.06e-24*nH2/(1+ropH2)/(1+1/5*np.exp(510/Tkin)*(1+54/nH2))*(1+R10)
Lambda_H2

8.68468331985239e-20

In [10]:
Y_factor=Gamma_pe/(Lambda_g_d+Lambda_CO+Lambda_Cp+Lambda_Oi+Lambda_H2)
Y_factor

array([0.05000109, 0.02000227, 0.00412922])